### ISSUE TITLE
Spectra display absolute scaling

### ISSUE THREAD

**Issue by AlexGKim** [skyportal/skyportal#2336] opened 2021-10-05 22:46 UTC
Each spectrum in the "Spectroscopy Plot" in a source page has different normalization.   We do not want the spectra to be renormalized, but rather maintain the flux scale.  This is because we are interested in the absolute time evolution of spectra. This seems inconsistent with #1051.

**Comment by AlexGKim** [comment] 2021-10-10 04:51
Perhaps there could be a toggle or configurable default?  For the DESI science application the non-normalization is important.

**Comment by guynir42** [comment] 2022-03-29 21:07
Closed as is a duplicate of #1846

**Closed by guynir42** 2022-03-29 21:07 UTC
