### ISSUE TITLE
Fix adding new user in Groups

### ISSUE THREAD

**Issue by profjsb** [skyportal/skyportal#897] opened 2020-09-12 16:37 UTC
When adding a user to a group that does not already exist on the site, there is an error that stops the user from being added (and an invite email to be generated for them):
![Kapture 2020-09-12 at 09 33 21](https://user-images.githubusercontent.com/480799/93000145-42907500-f4db-11ea-95ad-258366617f4f.gif)

Also, the lookup should be by username OR email for existing siteusers. The frontend should change to "Enter username or email".

**Comment by acrellin** [comment] 2020-09-12 16:49
@profjsb unable to reproduce. Also doesn't look like you're running master (slugified usernames)
See screen capture running latest master:

![invite](https://user-images.githubusercontent.com/7230285/93000405-28f02d00-f4dd-11ea-8462-ebf041ce389f.gif)

![image](https://user-images.githubusercontent.com/7230285/93000428-47eebf00-f4dd-11ea-834e-73414f8988c1.png)

**Comment by acrellin** [comment] 2020-09-12 16:54
@profjsb another screen capture of adding new users working as expected with invitations disabled on latest master:

![add_no_invite](https://user-images.githubusercontent.com/7230285/93000521-debb7b80-f4dd-11ea-881f-6a613d81aeb0.gif)

**Comment by profjsb** [comment] 2020-09-12 17:07
I'm running master now and getting this error still. Perhaps it's because I do not have sendgrid credentials?

**Comment by acrellin** [comment] 2020-09-12 17:15
@profjsb `git submodule update` -- then `make db_clear && make db_init`
This issue is not present on latest master with the pinned BL version. Note that the slugify PRs (SP and BL) are WIP and not merged. Comments related to those branches should go on those PRs.
Why did you reopen this?

**Comment by acrellin** [comment] 2020-09-12 17:15
See screenshots

**Closed by acrellin** 2020-09-12 17:15 UTC
Labels: bug, onboarding

**Comment by acrellin** [comment] 2020-09-12 17:20
@profjsb yes, if you have invitations enabled and don't have a valid sendgrid API key in the config, you'll see an error, but a more informative one than what you showed in the screen capture above. That one is perhaps related to the slugified usernames not working yet (make sure you're not running that BL commit)

**Comment by profjsb** [comment] 2020-09-12 17:49
See my comment/movie in the Slack
