### ISSUE TITLE
Perhaps we should define an `accessible_streams` parameter simllar to `accessible_groups`

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#1159] opened 2020-10-23 17:06 UTC
Perhaps we should define an `accessible_streams` parameter simllar to `accessible_groups`

_Originally posted by @dannygoldstein in https://github.com/skyportal/skyportal/pull/1125#discussion_r510547183_

**Comment by acrellin** [comment] 2020-10-23 17:07
Duplicate of https://github.com/skyportal/skyportal/issues/1158

**Closed by acrellin** 2020-10-23 17:07 UTC
