### ISSUE TITLE
alter user ACLs in manage users menu

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#1186] opened 2020-10-26 21:01 UTC
Currently only groups and streams are configurable in the user management page, would be nice if we could also configure ACLs through that page instead of having to modify the database directly.

**Comment by acrellin** [comment] 2020-10-27 16:53
Closing as duplicate of https://github.com/skyportal/skyportal/issues/914
@dannygoldstein this one's on my list for this week

**Closed by acrellin** 2020-10-27 16:53 UTC
