### ISSUE TITLE
The time is coming to update our good ol' bokeh lol

### ISSUE THREAD

**Issue by dmitryduev** [skyportal/skyportal#923] opened 2020-09-16 19:29 UTC
![image](https://user-images.githubusercontent.com/7557205/93383250-3593be80-f818-11ea-8bc2-225c9fc2f27a.png)

**Comment by dannygoldstein** [comment] 2020-11-18 03:40
Duplicate of #1250

**Closed by dannygoldstein** 2020-11-18 03:40 UTC
