### ISSUE TITLE
Download a followup spectrum from the front-end

### ISSUE THREAD

**Issue by scizen9** [skyportal/skyportal#1287] opened 2020-11-05 16:41 UTC
Currently there is no way to download a spectrum from fritz except to get the json reply from: https://fritz.science/api/sources/source_name/spectra.

On growth you had the option of downloading a fits version or an ascii version of the spectrum.

This is important because many users will want to run their own classification routine on the
followup spectra.

**Comment by dannygoldstein** [comment] 2020-11-05 20:04
Duplicate of #913

**Closed by dannygoldstein** 2020-11-05 20:04 UTC
